### ISSUE TITLE
Support for asciidoctor output

### ISSUE THREAD

**Issue by gdamore** [lambdalisue/rs-mdbook-alerts#19]
The asciidoc back end does not benefit from this work... which is unfortunate, because the asciidoc version of these alerts/callouts is trivial - for example:

```asciidoc
NOTE: Something wicked this way comes.
```
 
This would be superior to the output that is given now, which is to put it into a quote of some form.

(For the record, I'm here because I'm in the midst of converting a body of content from asciidoc to mdbook, but I need the ability to go back because ultimately asciidoctor's output for PDF and ePUB is vastly better than mdbook.)

**Comment by lambdalisue** [comment]
Unfortunately, this plugin is for HTML output and I don't think there is no room to support asciidoc.

**Comment by gdamore** [comment]
That's sad.  :( I *think* its possible to do this easily (trivial) for some formats other than HTML.  I'll explore some others -- it seems there are a lot of processors that do variants on this.

**Comment by lambdalisue** [comment]
@gdamore Well, I have no idea about asciidoctor so I may misunderstood your desire. If it 's trivial, PR is welcome 👍
