### ISSUE TITLE
Does not render properly with foldable callouts

### ISSUE THREAD

**Issue by CryptoMonkey** [lambdalisue/rs-mdbook-alerts#71]
SImple issue, in Obsidian you can set a callout to be default open or close like this --

Basic calloout with no defaule render state

> [!faq] Are callouts foldable?

You can set that is it be open by default by adding a '+'

> [!faq]+ Are callouts foldable?

And default closed by adding a '-'

> [!faq]- Are callouts foldable?

Adding either of these will cause the site to build via 'mdbook build', but the callout will not render correctly.  You get text blocked, but the icon is not rendered.  You get 

[!faq]-

as text instead.  Even if the extra character is ignored and the callout is always rendered open no matter the state requested it would be cleaner

**Comment by lambdalisue** [comment]
This renderer provides GitHub Markdown Alerts rather than Obsidian Callout. If GitHub Markdown Alerts support that syntax, I'll implement.

**Comment by CryptoMonkey** [comment]
Yes, you are right I was in the wrong tab - this belongs in rs-mdbook-callouts
